In [1]:
import numpy as np
from numpy import linalg as la
m=np.matrix([[1,2,3],[3,4,5],[5,4,3],[0,2,4],[1,3,5]])
U,S,V=la.svd(m, full_matrices=False)
# S[1]=0
# S[2]=0
print(U)
print(S)
print(V)
print(U.shape)
print(S.shape)
print(V.shape)
print(U*np.diag(S)*V)

# mt=np.transpose(m)
# print(m*mt)
# print(mt*m)
# print(la.eig(mt*m))
# print("___________")
# print(la.eig(m*mt))
# print(la.det(mt*m))

eng1=np.power(S[0],2)+np.power(S[1],2)

eng2=np.power(S[0],2)

print(eng2,eng1)

[[-0.29769568  0.15906393  0.90607622]
 [-0.57050856 -0.0332003   0.03827317]
 [-0.52074297 -0.73585663 -0.13315536]
 [-0.32257847  0.5103921  -0.18363343]
 [-0.45898491  0.41425998 -0.35511895]]
[  1.23922152e+01   3.92848616e+00   5.73316705e-16]
[[-0.40928285 -0.56345932 -0.7176358 ]
 [-0.81597848 -0.12588456  0.56420935]
 [-0.40824829  0.81649658 -0.40824829]]
(5, 3)
(3,)
(3, 3)
[[  1.00000000e+00   2.00000000e+00   3.00000000e+00]
 [  3.00000000e+00   4.00000000e+00   5.00000000e+00]
 [  5.00000000e+00   4.00000000e+00   3.00000000e+00]
 [  4.87069635e-16   2.00000000e+00   4.00000000e+00]
 [  1.00000000e+00   3.00000000e+00   5.00000000e+00]]
(153.56699645995911, 169.00000000000003)
